AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example
Metadata: {}
Parameters: {}
Mappings: {}
Conditions: {}
Outputs: {}
Globals:
  Function:
    Runtime: nodejs6.10
    Handler: index.handler
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /
            Method: GET
